language: node_js
node_js:
  - "0.12"
deploy:
  provider: heroku
  api_key:
    secure: Yjx02TI6mr+y5ZOQE+X1p45nTsmrAkG4ZNvitPFXW9HnLw5HwxTSX668tUJbp7T6lcGPrVHLNCut8SeyVwhxaIfZti2RZlHlHxnZDzr6fNupoCRdJUDqhMOPWonOEXakKxHYmo+LwsnCUejXFsdEnuInswV0NkCxgIU9GZewSRw=
  app:
    dev: protofit-dev
    master: protofit-staging
    production: protofit
